### ISSUE TITLE
Add an Endpoint for overall events

### ISSUE THREAD

**Issue by Frank-Wiebeler** [agrirouter-middleware/agrirouter-middleware#196]
# Why is this needed?
Currently, to poll for new Files in the Middleware, a poll for files needs to be done on every endpoint. This causes a lot of unrequired API calls. The described approach tries to handle this through polling of one single endpoint that lists all those endpoints that might need a call.

# What should be done?
Add an endpoint such as /secured/api/events that returns a list of all endpoints which registered an update "recently".
With Recently I mean either of 2 things:
1. Since the last X minutes where X is part of the App Configuration
2. Since the last call of the Events function

The Result should be a JSON Structure, providing an array of following Objects:

{
   endPointId: XXXXX
   events: [
     "endpoints",
     "files",
     "telemetry"
}

Event can be a list of up to 3 entries:
- endpoints: There was a recent change in the Endpoint List
- files: There was a recent change in the list of files
- telemetry: There were recently telemetry information received

**Comment by saschadoemer** [comment]
Please see:

#212 
#211 
#210 
#209
