### ISSUE TITLE
Feature Request: Rest API Call for getting connections between Endpoints

### ISSUE THREAD

**Issue by alexanderdemel** [agrirouter-middleware/agrirouter-middleware#274]
Hello,

For our Application it would be helpfull, if we have the possibility to get information about the connections between Endpoints via a REST API call. 
For example if I have one ExternalEndpointId I want to know how many ExternalVirtualEndpointIds are connected and maybe also which ExternalVirtualEndpointIds these are.

Best Regards

**Comment by saschadoemer** [comment]
It will be available with the next release, which is 7.4.0.

![image](https://github.com/agrirouter-middleware/agrirouter-middleware/assets/1309344/023dae7f-3ff5-413f-9b3d-4404eb3f905f)

**Comment by alexanderdemel** [comment]
Perfect! Thank you very much!
