### ISSUE TITLE
Exhausted Hiraki Database Pool

### ISSUE THREAD

**Issue by DustHoff** [agrirouter-middleware/agrirouter-middleware#276]
First finding after some digging in logs. There could be a possible relation to a business exception "[ERR_00003] Could not connect the MQTT client for the given endpoint with the ID". After many log entries with the given Exception, the Hiraki database pool is exhausted and can't recover. 

Further investigations will be provided in time.

**Comment by DustHoff** [comment]
On 19.05. at 22:30, the Database pool was exhausted again. Again many Exceptions about "[ERR_00003] Could not connect the MQTT client for the given endpoint with the ID 'ebe67126-f732-45e8-83de-xxxxxxxxxx'." is logged specifically only for one MQTT endpoint.

**Comment by saschadoemer** [comment]
Will be closed with #279
