### ISSUE TITLE
Dynamic Actuator Credentials

### ISSUE THREAD

**Issue by DustHoff** [agrirouter-middleware/agrirouter-middleware#338]
Currently, the Credentials for the actuator endpoints are created/defined after the first start. In the World of Kubernetes, in the case of self-healing deployments/applications, the actuator endpoints are already used during the first startup. This behavior makes an automated instance creation impossible.

Therefore, I suggest setting the actuator credentials by two environment variables—one for the username and another for the password. If the environment variables aren't set, the current behavior (credentials are generated) will be used. If the variables change during the lifetime of the CSFA instance, the new Credentials replace the old ones.

**Comment by saschadoemer** [comment]
@DustHoff will be fixed in the next release. A custom profile is added and credentials can be defined within the config.
