### ISSUE TITLE
Telemetry Platform Dashboard Error Web UI

### ISSUE THREAD

**Issue by alexanderdemel** [agrirouter-middleware/agrirouter-middleware#341]
When clicking on "Show Dashboard" from a Telemetryplattform (ExternalEndpointID - not virtual) on the Web UI an error message occurs. For virtual ExternalEndpointIds the Dashboard is working fine.

![Screenshot 2023-08-10 105041](https://github.com/agrirouter-middleware/agrirouter-middleware/assets/124699514/48fb68fa-2e54-460a-9d26-4a788c759335)

**Comment by saschadoemer** [comment]
@alexanderdemel will be fixed in the next release. Thanks for the input.
