### ISSUE TITLE
Missing documentation about router devices

### ISSUE THREAD

**Issue by julianklose** [agrirouter-middleware/agrirouter-middleware#377]
Since router devices are mandatory now, there should be some documentation about it. The OpenAPI doesn't really help.

```json
{
  "routerDevice": {
    "deviceAlternateId": "string",
    "authentication": {
      "type": "PEM",
      "secret": "string",
      "certificate": "string"
    },
    "connectionCriteria": {
      "clientId": "string",
      "host": "string",
      "port": "string"
    }
  }
}
```
How do I get these parameters?

**Comment by saschadoemer** [comment]
You are able to receive a router device from the agrirouter if you are a registered developer.

You can create a new router device and download the connection details as P12 or PEM certificates, see the screenshots attached.

Navigate to the router device section.

![Screenshot_20231116_134223_Chrome.jpg](https://github.com/agrirouter-middleware/agrirouter-middleware/assets/1309344/255d13d9-2124-4e87-962a-7b28130ee180)

Create a new router device.

![Screenshot_20231116_134241_Chrome.jpg](https://github.com/agrirouter-middleware/agrirouter-middleware/assets/1309344/56c8c0c1-67ed-4f11-bded-2b1a3c617824)


Select the router device and download the the connection details.

![Screenshot_20231116_134305_Chrome.jpg](https://github.com/agrirouter-middleware/agrirouter-middleware/assets/1309344/061ffa46-f7f8-4698-9533-8a152d4adf3e)

![Screenshot_20231116_134328_Chrome.jpg](https://github.com/agrirouter-middleware/agrirouter-middleware/assets/1309344/518d38a9-182b-4b63-86a0-5bd6e6e089b7)

![Screenshot_20231116_134347_Chrome.jpg](https://github.com/agrirouter-middleware/agrirouter-middleware/assets/1309344/c8c5596e-684a-4454-bff7-5b9566440f92)


The JSON can be used as body for the request.

**Comment by saschadoemer** [comment]
Has been there since the beginning, but was a feature rarely used. To ensure that there are not more MQTT connections than necessary it was a quite logical step to make it mandatory for an application. And since the certificates are valid for 10 years it is nearly free of maintenance.

I will add a section to the functional documentation, good suggestion 👌🏻

**Comment by saschadoemer** [comment]
Closed with the latest commit on the `main` branch.
