### ISSUE TITLE
More details for the endpoint in case onboarding fails

### ISSUE THREAD

**Issue by saschadoemer** [agrirouter-middleware/agrirouter-middleware#90]
com.dke.data.agrirouter.api.exception.OnboardingException: There was an error '22' during the onboarding process, details were 'The application certification version ID is not in the proper status for this request.'

**Comment by michaldolnik** [comment]
Have you please found what does this error mean?

**Comment by saschadoemer** [comment]
@michaldolnik the cause of the error is already clear for me. This is just an reminder to implement the details within the application. If you have such an error, please check if your application is in the status "Approved for testing" or "Approved". If it is just approved, the user getting the error has to be invited as a tester from your developer account. If you have any questions, feel free to contact me via agrirouter Slack channel 👌🏻

**Comment by michaldolnik** [comment]
Thank you for clarifying that!
